### ISSUE TITLE
Build and flashing the firmware

### ISSUE THREAD

**Issue by easy98** [bitcraze/crazyflie-release#8]
Hi,

If I directly download the source code here rather than git clone it, is there anyway I can build it, since I want to do some experiments based on the old version of firmware? Thanks!
![image](https://user-images.githubusercontent.com/71677216/126747120-af83749d-0fdd-473e-ad3f-6140488848e0.png)

**Comment by knmcguire** [comment]
That is much easier to do that in Git. You can easily make a branch based on the tag of the release in the crazyflie firmware:

```
git checkout -b newbranch 2020.09
```

The last one is the tag of the release, which you can check here. https://github.com/bitcraze/crazyflie-firmware/tags

**Comment by ataffanel** [comment]
This source is the source of the release script, this is likely not what you want to do since this release script only download firmware from github releases and will reproduce the .zip that is already available in this repos.

@knmcguire git command is what you likely need to do in the firmware repos you are interested into, both crazyflie-firmware and crazyflie2-nrf-firmware are present in the .zip. There is unfortunately no easy way to rebuild a .zip from a random build, but the zip format is not complex so this can be done manually by copying the .bin in an existing zip or by making a custom script.

**Comment by easy98** [comment]
Thank you for your reply, but how can I copy the .bin in an existing zip, and what's is the existing zip?

**Comment by ataffanel** [comment]
I am talking about the .zip files in the screenshot you took: if you open `firmware-cf2-2020.09.zip` it does contains .bin files for both nrf (cf2_nrf) and stm (cf2) firmwares as well as a manifest.json file describing the content.

**Comment by easy98** [comment]
Thank you for your quick reply! Finally, I directly clone the old versions of firmware by cloning a particular tag:

`git clone --recursive --branch 2020.09 https://github.com/bitcraze/crazyflie-firmware.git `

It can solve this issue.
